import streamlit as st
import pandas as pd
import os

# --- 1. CONFIGURATION AND DATA LOADING (Run once) ---

# Set overall app configuration
st.set_page_config(
    page_title="Course Project Dashboard (Multi-Data)", 
    layout="wide",
    initial_sidebar_state="expanded"
)

# Define the file paths for the student datasets
DATA_FILES = {
    'st1_df': os.path.join('data', 'st1_data.csv'), # Sports Results
    'st2_df': os.path.join('data', 'st2_data.csv'), # Exam Results
    'st3_df': os.path.join('data', 'st3_data.csv')  # Spotify Data
}

@st.cache_data
def load_all_student_data():
    """
    Loads all student CSV files into a dictionary of DataFrames using caching.
    This function ensures data is loaded only once and shared across all pages.
    """
    data_dict = {}
    
    # Check if data directory and files exist
    for key, path in DATA_FILES.items():
        if os.path.exists(path):
            try:
                data_dict[key] = pd.read_csv(path)
            except Exception as e:
                st.error(f"Error loading data from {path}: {e}")
                data_dict[key] = pd.DataFrame()
        else:
            # IMPORTANT: Display a clear warning if data is missing.
            st.warning(f"Data file not found: {path}. Please ensure 'data/' folder exists and run 'generate_data.py'.")
            data_dict[key] = pd.DataFrame()
    return data_dict

# Initialize Session State for Data (This is available to ALL pages)
if 'student_data' not in st.session_state:
    st.session_state['student_data'] = load_all_student_data()

# --- 2. HOME PAGE CONTENT ---

st.title("Welcome to the Course Project Dashboard! 🎓")
st.markdown("""
This dashboard template is designed to showcase multiple independent student analyses, each using its own dataset.
All data loading is handled centrally here, and the results are displayed on the individual pages listed in the sidebar.

### Project Structure Instructions
1.  **Main Directory:** Contains this file (`🏠_Home_Page.py`).
2.  **Data Folder:** The `data/` folder contains the three CSV files generated by `generate_data.py`.
3.  **Pages Folder:** The `pages/` folder contains the individual student project files (e.g., `01_...py`, `02_...py`).

👈 **Select an analysis from the sidebar to view a student's project!**
""")

st.subheader("Data Summary")

# Simple check to show which datasets loaded successfully
summary_data = {
    "Dataset": ["st1_df (Sports)", "st2_df (Exams)", "st3_df (Spotify)"],
    "Status": ["Loaded" if not st.session_state['student_data']['st1_df'].empty else "Missing",
               "Loaded" if not st.session_state['student_data']['st2_df'].empty else "Missing",
               "Loaded" if not st.session_state['student_data']['st3_df'].empty else "Missing"],
    "Rows": [len(st.session_state['student_data']['st1_df']),
             len(st.session_state['student_data']['st2_df']),
             len(st.session_state['student_data']['st3_df'])]
}
st.table(summary_data)